# prepare_all_gold_standards.r
# This script prepares the gold standard sensitive genes
# Gold standard sensitive genes are identified as the genes that a cell is particularly sensitive to losing relative to other cells of the same lineage
# If static thresholds are supplied, also considers highly sensitive genes even if that cell is not an outlier

# Load Required Packages
message("Loading Packages")
suppressPackageStartupMessages (library(optparse, quietly = T))
suppressPackageStartupMessages (library(tidyverse, quietly = T))
suppressPackageStartupMessages (library(readxl, quietly = T))

# Handling input arguments
option_list = list(
  make_option(c("-z", "--zscore"), type="double", default=2.0, 
              help="z-score threshold to be used (default = 2.0)", metavar ="z score"),
  make_option(c("-d", "--dependency"), type="double", default=0.9, 
              help="static threshold for gene dependency (default = 0.9). Set as FALSE to not use static thresholds", metavar ="Dependency"),
  make_option(c("-s", "--sensitivity"), type="double", default=2.0, 
              help="static threshold for drug sensitivity (default = 2.0). Set as FALSE to not use static thresholds", metavar ="Sensitivity")
); 

opt_parser = OptionParser(option_list=option_list);
opt = parse_args(opt_parser);

th <- opt$zscore
dependency_static_th <- opt$dependency
drug_sensitivity_static_th <- opt$sensitivity

#############################
# Functions
###############################

get_z_scores <- function(Matrix){
  Sd   <- apply(Matrix, 2, function(x) sd(x, na.rm=T))
  Mean <- apply(Matrix, 2, function(x) mean(x, na.rm=T))
  centered <- t(t(Matrix) - Mean)
  z_scores <- t(t(centered) / Sd)
  return(z_scores)
}


#############################
# Get cell list
###############################
# This cell list is generated by the choose_cells.r script

cell_list <- read_csv("data/cell_list.csv")

#############################
# Get cell line information
#############################

CCLE_sample_info <- read_csv("data/CCLE/Model.csv") %>%
  dplyr::select(DepMap_ID=ModelID, lineage=OncotreeLineage, cell_ID=StrippedCellLineName) %>%
  filter(cell_ID %in% cell_list$cell_ID) %>%
  unique()

#############################
# Read In Data
#############################
message("Reading in data")

dependency <- fread("data/CCLE/CRISPRGeneDependency.csv") %>%
  as.data.frame() %>%
  inner_join(CCLE_sample_info[c("DepMap_ID","cell_ID")], by = c("ModelID"="DepMap_ID")) %>%
  dplyr::select(-ModelID) %>%
  column_to_rownames("cell_ID")

colnames(dependency) <- gsub(" \\(.*","", colnames(dependency))
dependency <- dependency[!duplicated(colnames(dependency))]

# Getting GDSC versions of cell_IDs
GDSC_IDs <- read_xlsx("data/GDSC/Cell_Lines_Details.xlsx",sheet = "Cell line details") %>%
  dplyr::select(GDSC_ID = `Sample Name`, COSMIC_ID = `COSMIC identifier`) %>%
  mutate(cell_ID = toupper(gsub("[[:punct:], ]", "", GDSC_ID)))

# Getting all possible synonyms of each drug and choosing a primary name to map all synonyms back to
drug_synonyms <- read.csv("data/GDSC/screened_compounds_rel_8.4.csv") %>%
  dplyr::select(DRUG_NAME, SYNONYMS) %>%
  mutate(synonym_0 = DRUG_NAME,
         n_synonyms = nchar(gsub("[^,]","", SYNONYMS))+1)
drug_synonyms <- drug_synonyms %>%
  separate(SYNONYMS, sep = ",", into = paste("synonym", 1:max(drug_synonyms$n_synonyms, na.rm = T))) %>%
  dplyr::select(-n_synonyms) %>%
  pivot_longer(cols = -DRUG_NAME, names_to = "category", values_to = "synonyms") %>%
  dplyr::select(primary_name = DRUG_NAME, synonyms) %>%
  na.omit() %>%
  mutate(primary_name = toupper(gsub("[[:punct:], ]", "", primary_name)),
         synonyms = toupper(gsub("[[:punct:], ]", "", synonyms))) %>%
  unique() %>%
  filter(synonyms != "")

# Reading in drug sensitivity data (firstly, GDSC1)
GDSC1 <- read_xlsx("data/GDSC/GDSC1_fitted_dose_response_24Jul22.xlsx") %>%
  dplyr::select(DATASET,COSMIC_ID, DRUG_ID, DRUG_NAME, LN_IC50, original_z_score = Z_SCORE) %>%
  inner_join(GDSC_IDs, by = "COSMIC_ID") %>% dplyr::select(-GDSC_ID, -COSMIC_ID) %>%
  dplyr::relocate(cell_ID) %>%
  unique() %>%
  na.omit()

GDSC2 <- read_xlsx("data/GDSC/GDSC2_fitted_dose_response_24Jul22.xlsx") %>%
  dplyr::select(DATASET,COSMIC_ID, DRUG_ID, DRUG_NAME, LN_IC50, original_z_score = Z_SCORE) %>%
  inner_join(GDSC_IDs, by = "COSMIC_ID") %>% dplyr::select(-GDSC_ID, -COSMIC_ID) %>%
  dplyr::relocate(cell_ID) %>%
  unique() %>%
  na.omit()

GDSC <- rbind(GDSC1, GDSC2) %>%
  mutate(DRUG_NAME = toupper(gsub("[[:punct:], ]", "", DRUG_NAME)))

rm(GDSC1, GDSC2)

# Get drug-gene ineteractions from DGIdb

DGIdb <- fread("data/DGIdb/interactions.tsv", sep = "\t")

drug_types <- DGIdb$interaction_types %>% unique() %>% sort() 
# Selecting only inhibitory interaction types
drug_types <- drug_types[c(7,10,11,12,13,14,16,18,19,20,22,25)]

write_csv(data.frame(drug_types),"data/DGIdb/selected_drug_types.csv")

DGIdb <- DGIdb %>% 
  pivot_longer(cols = drug_claim_name:drug_name, names_to = "name_category", values_to = "drug_name") %>%
  mutate(drug_name = toupper(gsub("[[:punct:], ]", "", drug_name))) %>%
  inner_join(drug_synonyms, by = c("drug_name"="synonyms")) %>%
  dplyr::select(gene_name, drug=primary_name,interaction_types) %>%
  filter(interaction_types %in% drug_types) %>%
  unique() %>%
  na.omit()

GDSC <- GDSC %>%
  left_join(DGIdb, by = c("DRUG_NAME"="drug"))

# At this point, we can quickly take the full list of possible genes
total_genes <- union(GDSC$gene_name, colnames(dependency))

GDSC <- GDSC %>%
  dplyr::select(DATASET, cell_ID, DRUG_NAME, gene_name, LN_IC50) %>%
  unique() %>%
  mutate(target_ID = paste(DATASET,DRUG_NAME, gene_name, sep = "_")) %>%
  dplyr::select(cell_ID, target_ID, LN_IC50) %>%
  # Taking average of replicate data  
  group_by(cell_ID, target_ID) %>%
  summarise(LN_IC50 = mean(LN_IC50)) %>%
  pivot_wider(names_from = "target_ID", values_from = "LN_IC50")





for(lin in sort(unique(CCLE_sample_info$lineage))){
  message(paste0("Identifying gold standards for ", lin, " cells"))
  
  lineage_cells <- CCLE_sample_info %>% filter(lineage==lin) %>% dplyr::select(-lineage)
  
  if(length(which(lineage_cells$DepMap_ID %in% dependency$ModelID)) >= 4){
      
    
    
    #############################
    # Gene Dependency
    #############################
    
    # Probabilities of dependency are calculated for each gene score in a cell line as the probability 
    # that score arises from the distribution of essential gene scores rather than nonessential gene scores. 
    # “Probability of dependency” is essentially modeling the gene effect as either being sampled from the 
    # distribution arising from “essential” genes or “non-essential” genes, and being a probability, the values range from 0 to 1.
    
    lin_dependency_matrix <- dependency %>%
      rownames_to_column("cell_ID") %>%
      filter(cell_ID %in% lineage_cells$cell_ID)
      column_to_rownames("cell_ID")
    
    
    lin_dependency <- lin_dependency_matrix %>%
      # First adding a row of dependency means for each gene across the cells
      rbind(
        colMeans(lin_dependency_matrix) %>% 
          matrix(nrow = 1, dimnames = list("dependency_mean",colnames(lin_dependency_matrix)))
        ) %>%
      # Transposing data
      rownames_to_column("cell_ID") %>%
      data.table::transpose(make.names = "cell_ID", keep.names = "gene_ID") %>%
      pivot_longer(cols = -c(gene_ID, dependency_mean), names_to = "cell_ID", values_to = "dependency") %>%
      # Then joining with z-scores and calculated outliers
      inner_join(
        # Sqrt data to force normal distribution
        get_z_scores(sqrt(lin_dependency_matrix)) %>%
          as.data.frame() %>%
          rownames_to_column("cell_ID") %>%
          pivot_longer(cols = -cell_ID, names_to = "gene_ID", values_to = "z") %>%
          mutate(outlier = z > th),
        by = c("gene_ID", "cell_ID")
      ) %>%
      # Defining outliers as dependent genes as long as their dependency score is > 0.5
      mutate(dependent = ifelse(outlier & dependency > 0.5, TRUE, FALSE)) %>%
      dplyr::select(cell_ID, gene_ID, dependency, dependency_mean, z, dependent)
    
    if(dependency_static_th != FALSE){
      lin_dependency <- lin_dependency %>%
        mutate(dependent = ifelse(dependency > dependency_static_th, TRUE, dependent))
      
    }
    
    rm(lin_dependency_matrix)
  
  }
  
  if(length(which(lineage_cells$cell_ID %in% GDSC$cell_ID)) >= 4){
  
    #############################
    # Drug Sensitivity
    #############################
    
    # Available from GDSC with z-scores (one cell vs all other cells) as well as ln(IC50)
    # We use provided z-scores for static thresholds and calculate new lineage-specific z-scores to identify outliers
    
  
    
    lin_GDSC_matrix <- GDSC %>%
      filter(cell_ID %in% lineage_cells$cell_ID) %>%
      column_to_rownames("cell_ID")
    
    lin_drug_sensitivity <- lin_GDSC_matrix %>%
      
      # First getting original sentitivty and gene-wise sentitivty means
      rbind(colMeans(lin_GDSC_matrix, na.rm = T) %>% 
              matrix(nrow = 1, dimnames = list("IC50_mean",colnames(lin_GDSC_matrix)))
            ) %>%
      # Transposing data
      rownames_to_column("cell_ID") %>%
      data.table::transpose(make.names = "cell_ID", keep.names = "target_ID") %>%
      pivot_longer(cols = -c(target_ID, IC50_mean), names_to = "cell_ID", values_to = "IC50") %>%
      # Then joining with z-scores and calculated outliers
      inner_join(
        get_z_scores(lin_GDSC_matrix) %>%
          as.data.frame() %>%
          rownames_to_column("cell_ID") %>%
          pivot_longer(cols = -cell_ID, names_to = "target_ID", values_to = "z") %>%
          mutate(outlier = z < -th),
        by = c("target_ID", "cell_ID")
      ) %>%
      mutate(IC50 = round(exp(IC50), 2), IC50_mean = round(exp(IC50_mean)), 2) %>%
      # Defining outliers as sensitive
      mutate(sensitive = ifelse(outlier, TRUE, FALSE)) %>%
      dplyr::select(cell_ID, target_ID, IC50, IC50_mean, z, sensitive) %>%
      separate(target_ID, into = c("dataset", "drug_name", "gene_ID")) %>%
      relocate(dataset)
    
    if(drug_sensitivity_static_th != FALSE){
      lin_drug_sensitivity <- lin_drug_sensitivity %>%
        # Bring back original z_scores and define universally sensitive genes as sensitive
        left_join(GDSC %>% dplyr::select(DATASET, cell_ID, DRUG_NAME, original_z_score), by = c("dataset"="DATASET", "cell_ID", "drug_name"="DRUG_NAME")) %>%
        mutate(sensitive = ifelse(original_z_score < -drug_sensitivity_static_th, TRUE, sensitive))
    }
    
    rm(lin_GDSC_matrix)
  
  }
  
  
    
  
  
  if(length(which(lineage_cells$DepMap_ID %in% dependency$ModelID)) < 4 & length(which(lineage_cells$cell_ID %in% GDSC$cell_ID)) < 4){
    next
  }
  
  if(length(which(lineage_cells$DepMap_ID %in% dependency$ModelID)) < 4){
    lin_gold_standards <- lin_drug_sensitivity %>% 
      dplyr::select(cell_ID, gene_ID, sensitive) %>%
      mutate(is_gold_standard = sensitive) %>%
      filter(is_gold_standard) %>%
      unique() %>%
      mutate(lineage = lin, dependent = FALSE) %>%
      dplyr::select(cell_ID,gene_ID,dependent,sensitive,is_gold_standard,lineage)
  }else if(length(which(lineage_cells$cell_ID %in% GDSC$cell_ID)) < 4){
    lin_gold_standards <- lin_dependency %>% 
      dplyr::select(cell_ID, gene_ID, dependent) %>%
      mutate(is_gold_standard = dependent) %>%
      filter(is_gold_standard) %>%
      unique() %>%
      mutate(lineage = lin, sensitive = FALSE) %>%
      dplyr::select(cell_ID,gene_ID,dependent,sensitive,is_gold_standard,lineage)
  }else{
    
  #############################
  # Combined Gold Standards
  #############################
  
  lin_gold_standards <- full_join(
    lin_dependency %>% dplyr::select(cell_ID, gene_ID, dependent),
    lin_drug_sensitivity %>% dplyr::select(cell_ID, gene_ID, sensitive),
    by = c("cell_ID", "gene_ID")
    ) %>%
    mutate(is_gold_standard = ifelse(dependent, TRUE, ifelse(sensitive, TRUE, FALSE))) %>%
    filter(is_gold_standard) %>%
    unique() %>%
    mutate(lineage = lin)
  
  }
  
  if(lin == sort(unique(CCLE_sample_info$lineage))[1]){
    gold_standards <- lin_gold_standards
  }else{
    gold_standards <- rbind(gold_standards, lin_gold_standards)
  }
  
  
}

# This summary shows what percentage of the total genes with available information (~17500 genes) the cells have been identified as being sensitive to, on average
# per lineage

summary <- gold_standards %>%
  group_by(lineage,cell_ID) %>%
  summarise(total = n(), drug_sensitive = sum(sensitive, na.rm = T), gene_dependent = sum(dependent, na.rm = T)) %>%
  group_by(lineage) %>%
  summarise(mean_total_percentile_genes = mean(total)/length(total_genes)*100, 
            max_total_percentile_genes = max(total)/length(total_genes)*100, 
            min_total_percentile_genes = min(total)/length(total_genes)*100,
            mean_gene_dependent_percentile_genes = mean(gene_dependent)/length(total_genes)*100, 
            mean_drug_sensitive_percentile_genes = mean(drug_sensitive)/length(total_genes)*100)

write_csv(summary,"validation_data/summary_gold_standards.csv")
